// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjW3fbDo0ljLMn7p--LSoKsbtLIb96zm4',
    appId: '1:936239637335:web:96a32f4574e903f231d412',
    messagingSenderId: '936239637335',
    projectId: 'twapp-firebase',
    authDomain: 'twapp-firebase.firebaseapp.com',
    storageBucket: 'twapp-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSmiFxjYZ2pqPfVuX6Bszj50L3tsX80uw',
    appId: '1:936239637335:android:88b8183bd473606031d412',
    messagingSenderId: '936239637335',
    projectId: 'twapp-firebase',
    storageBucket: 'twapp-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHY9k3VisMFuXutpX0JtA0kLJK7DWg0-o',
    appId: '1:936239637335:ios:f3c8bc2797941b3531d412',
    messagingSenderId: '936239637335',
    projectId: 'twapp-firebase',
    storageBucket: 'twapp-firebase.appspot.com',
    iosClientId: '936239637335-lj8a6van0bc4mbjatclq8do7gc31uvpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.twapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHY9k3VisMFuXutpX0JtA0kLJK7DWg0-o',
    appId: '1:936239637335:ios:f3c8bc2797941b3531d412',
    messagingSenderId: '936239637335',
    projectId: 'twapp-firebase',
    storageBucket: 'twapp-firebase.appspot.com',
    iosClientId: '936239637335-lj8a6van0bc4mbjatclq8do7gc31uvpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.twapp',
  );
}
